export const bairrosVarzeaGrande = [
  "7 De Maio",
  "24 De Dezembro",
  "Água Limpa",
  "Água Vermelha",
  "Alameda",
  "Alto da Boa Vista",
  "Asa Bela",
  "Bonsucesso",
  "Centro",
  "Centro Norte",
  "Centro Sul",
  "Carrapicho",
  "Cabo Michel",
  "Capão do Pequi",
  "Chapéu do sol",
  "Capão Grande",
  "Capela do Piçarrão",
  "Cidade de Deus",
  "Cohab Asa Branca",
  "Cohab Canelas",
  "Cohab Cristo Rei",
  "Cohab Dom Orlando Chaves",
  "Cohab Jaime Campos",
  "Cohab João Baracat",
  "Cohab Jardim Primavera",
  "Canelas",
  "Colinas Verdejantes",
  "Construmat",
  "Costa Verde",
  "Dom Diego",
  "Distrito Industrial",
  "Domingos Sávio",
  "Engordador",
  "Figueirinha",
  "Frutal de Minas",
  "Glória",
  "Hélio Ponce",
  "Industrial I",
  "Industrial II",
  "Industrial III",
  "Industrial IV",
  "Jardim Alá",
  "Jardim América",
  "Jardim Buenos Aires",
  "Jardim Cerrado",
  "Jardim Costa Verde",
  "Jardim Campos Verdes",
  "Jardim das Oliveiras",
  "Jardim dos Estados",
  "Jardim Eldourado",
  "Jardim Esmeralda",
  "Jardim Glória I",
  "Jardim Glória II",
  "Jardim Imperador",
  "Jardim Icaraí",
  "Jardim Imperial",
  "Jardim Itororó",
  "Jardim Ipanema",
  "Jardim Manaíra",
  "Jardim Kataguás",
  "Jardim Manancial",
  "Jardim Marajoara",
  "Jardim Marajoara II",
  "Jardim Mariana",
  "Jardim Novo Horizonte",
  "Jardim Novo Mundo",
  "Jardim Ouro Verde",
  "Jardim Panorama",
  "Jardim Paula I",
  "Jardim Paula II",
  "Jardim Potiguar",
  "Jardim União",
  "Jardim Rodrigues",
  "Jardim Vista Alegre",
  "Jardim Vitória Régia",
  "Jeani",
  "Lagoa do Jacaré",
  "Limpo Grande",
  "Loteamento Joaquim Curvo",
  "Loteamento Parque do Jatobá",
  "Marajoara",
  "Mapim",
  "Maringá I",
  "Maringá II",
  "Maringá III",
  "Monte Castelo",
  "Nair Sacre",
  "Nova Esperança",
  "Nova Fronteira",
  "Novo Mato Grosso",
  "Nova Várzea Grande",
  "Novo Mundo",
  "Nossa Senhora da Guia",
  "Ouro Branco",
  "Ouro Verde",
  "Pai André",
  "Pampulha",
  "Panamericano",
  "Parque Del Rei",
  "Parque Atlântico",
  "Parque do Lago",
  "Parque Mangabeiras",
  "Parque Sabiá",
  "Parque São João",
  "Parque Cabo Michel",
  "Paiaguás",
  "Pirinéu",
  "Planalto Ipiranga",
  "Planalto Beira Rio",
  "Ponte Nova",
  "Portal da Amazônia",
  "Praia Grande",
  "Princesa do Sol",
  "Residencial Jacarandá",
  "Residencial Santa Clara",
  "Residencial São Francisco",
  "Santa Izabel",
  "São Benedito",
  "Santa Luzia",
  "Santa Maria I",
  "Santa Maria II",
  "São Marcos",
  "São Mateus",
  "São Mateus II",
  "São Simão",
  "Serra Dourada",
  "Souza Lima",
  "Treze de Setembro",
  "Terra Nova",
  "Unipark",
  "Vila Artur",
  "Vila Operária",
  "Vila São João",
  "Vinte e Três de Setembro",
  "Vitória Régia",
  "Vila Ipase"
];

export const redeOptions = ['Pr. Heloisa', 'Pr. Rafael', 'Pr. Ray Raikson', 'Obr. Bruno', 'Obr. Ivan'];
export const discipuladoOptions = ['Adilson', 'Lucas', 'Felipe Coelho', 'Daniele'];
